# Generated by Django 5.1.1 on 2024-11-08 11:50

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='fullname', unique=True)),
                ('picture', models.ImageField(max_length=200, upload_to='teachers/', verbose_name="O'qituvchi rasmi")),
                ('fullname', models.CharField(max_length=200, verbose_name="O'qituvchi FIOsi")),
                ('content', models.TextField(verbose_name="O'qituvchi haqida ma'lumot")),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram manzili')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook manzili')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='LinkedIn manzili')),
            ],
            options={
                'verbose_name': "O'qituvchi ",
                'verbose_name_plural': "O'qituvhchilar ",
            },
        ),
    ]
