# Generated by Django 5.1.1 on 2025-01-11 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_remove_language_description_remove_language_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Rasm')),
                ('answer', models.CharField(blank=True, max_length=150, null=True, verbose_name='Javob')),
                ('has_options', models.BooleanField(default=True, verbose_name='Variantlar mavjud')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('submitters', models.IntegerField(default=0, verbose_name='Yuboruvchilar soni')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.language', verbose_name='Til')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Variant')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri variant")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multilevel.question', verbose_name='Variant savoli')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('submitters', models.IntegerField(default=0, verbose_name='Yuboruvchilar soni')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.language', verbose_name='Til')),
            ],
        ),
        migrations.CreateModel(
            name='Speaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('picture', models.ImageField(upload_to='speaking/', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('submitters', models.IntegerField(default=0, verbose_name='Yuboruvchilar soni')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.language', verbose_name='Til')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('picture', models.ImageField(upload_to='tests/pictures/', verbose_name='Rasm')),
                ('audio', models.FileField(upload_to='tests/audio/', verbose_name='Audio')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Test matni')),
                ('options', models.TextField(blank=True, null=True, verbose_name='Variantlar')),
                ('constraints', models.TextField(blank=True, null=True, verbose_name='Shartlar')),
                ('order', models.PositiveSmallIntegerField()),
                ('listening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multilevel.listening', verbose_name='Listening')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multilevel.reading', verbose_name='Reading')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multilevel.test', verbose_name='Savol testi'),
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('picture', models.ImageField(upload_to='writing/', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('task1', models.TextField()),
                ('task2', models.TextField()),
                ('submitters', models.IntegerField(default=0, verbose_name='Yuboruvchilar soni')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.language', verbose_name='Til')),
            ],
        ),
    ]
