# Generated by Django 5.1.1 on 2025-01-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='sample',
            field=models.TextField(blank=True, null=True, verbose_name='Misol'),
        ),
    ]
