# Generated by Django 5.1.1 on 2025-01-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0002_test_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='tests/audio/', verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='test',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='tests/pictures/', verbose_name='Rasm'),
        ),
    ]
