# Generated by Django 5.1.1 on 2025-01-12 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_language_description_remove_language_duration_and_more'),
        ('multilevel', '0003_alter_test_audio_alter_test_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_listening', models.BooleanField(default=False)),
                ('listening_result', models.PositiveSmallIntegerField(default=0, verbose_name='Listening natijasi')),
                ('listening_user_options', models.JSONField(blank=True, null=True)),
                ('done_reading', models.BooleanField(default=False)),
                ('reading_result', models.PositiveSmallIntegerField(default=0, verbose_name='Reading natijasi')),
                ('reading_user_options', models.JSONField(blank=True, null=True)),
                ('done_writing', models.BooleanField(default=False)),
                ('result', models.PositiveSmallIntegerField(default=0, verbose_name='Writing natijasi')),
                ('writing_user_options', models.JSONField(blank=True, null=True)),
                ('done_speaking', models.BooleanField(default=False)),
                ('speaking_result', models.PositiveSmallIntegerField(default=0, verbose_name='Speaking natijasi')),
                ('speaking_user_options', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.language', verbose_name='Til')),
                ('listening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multilevel.listening', verbose_name='Listening')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multilevel.reading', verbose_name='Reading')),
                ('speaking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multilevel.speaking', verbose_name='Speaking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('writing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multilevel.writing', verbose_name='Writing')),
            ],
        ),
    ]
