# Generated by Django 5.1.1 on 2025-01-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0004_usertest'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='text_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Matn sarlavhasi'),
        ),
    ]
