# Generated by Django 5.1.1 on 2025-01-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0005_test_text_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Sarlavha'),
        ),
    ]
