# Generated by Django 5.1.1 on 2025-01-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0006_alter_test_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
    ]
