# Generated by Django 5.1.1 on 2025-01-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0007_alter_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='writing',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='writing/', verbose_name='Rasm'),
        ),
    ]
