# Generated by Django 5.1.1 on 2024-11-08 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.RenameField(
            model_name='option',
            old_name='isCorrect',
            new_name='is_correct',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='leaners',
        ),
        migrations.AddField(
            model_name='direction',
            name='learners',
            field=models.IntegerField(default=0, verbose_name="O'quvchilar soni"),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='Savol testi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default=1, verbose_name='Savol matni'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direction',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.language', verbose_name='Til'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='mark',
            field=models.IntegerField(default=0, verbose_name='Bahosi'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='picture',
            field=models.ImageField(upload_to='directions/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.direction', verbose_name="Yo'nalish"),
        ),
        migrations.AlterField(
            model_name='exam',
            name='picture',
            field=models.ImageField(upload_to='exams/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='submitters',
            field=models.IntegerField(default=0, verbose_name='Yuboruvchilar soni'),
        ),
    ]
