# Generated by Django 5.1.1 on 2024-11-08 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_question_options_and_more'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.language', verbose_name='Til'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
