# Generated by Django 5.1.1 on 2024-11-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_direction_language_delete_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
            ],
        ),
    ]
