# Generated by Django 5.1.1 on 2025-01-11 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_quizlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Imtixon matni'),
        ),
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='listening/', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('submitters', models.IntegerField(default=0, verbose_name='Yuboruvchilar soni')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.direction', verbose_name="Yo'nalish")),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='listening',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.listening', verbose_name='Listening'),
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('picture', models.ImageField(upload_to='reading/', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('submitters', models.IntegerField(default=0, verbose_name='Yuboruvchilar soni')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.direction', verbose_name="Yo'nalish")),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='reading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.reading', verbose_name='Reading'),
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('picture', models.ImageField(upload_to='writing/', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('submitters', models.IntegerField(default=0, verbose_name='Yuboruvchilar soni')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.direction', verbose_name="Yo'nalish")),
            ],
        ),
    ]
