# Generated by Django 5.1.1 on 2025-01-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_text_listening_exam_listening_reading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='listening',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='reading',
        ),
        migrations.RemoveField(
            model_name='writing',
            name='direction',
        ),
        migrations.DeleteModel(
            name='Listening',
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
        migrations.DeleteModel(
            name='Writing',
        ),
    ]
