# Generated by Django 5.1.1 on 2024-11-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='flag',
            field=models.CharField(max_length=8),
        ),
    ]
