# Generated by Django 5.1.1 on 2025-01-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_language_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='languages/'),
        ),
    ]
