# Generated by Django 5.1.1 on 2025-01-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_language_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
