# Generated by Django 5.1.1 on 2025-01-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_language_description_language_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='description',
        ),
        migrations.RemoveField(
            model_name='language',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='language',
            name='price',
        ),
    ]
